var countrynames = ["India", "Pakistan", "Bangladesh", "Nepal", "Afghanistan"];
var country1 = countrynames[0],
  country2 = countrynames[1],
  country3 = countrynames[2],
  country4 = countrynames[3],
  country5 = countrynames[4];
console.log("Country 1 = ", country1);
console.log("Country 2 = ", country2);
console.log("Country 3 = ", country3);
console.log("Country 4 = ", country4);
console.log("Country 5 = ", country5);
